[package]
name = "kfc-descriptor"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
kfc = { package = "kfc-base", path = "../kfc-base" }

thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
