name: Build and Test KFC Parser

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  kfc-parser:
    strategy:
      matrix:
        toolchain:
          - stable
        platform:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: kfc-parser.exe

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Cache Cargo registry
        uses: Swatinem/rust-cache@v2

      - name: Build Debug
        run: cargo build --locked --verbose --target ${{ matrix.platform.target }}

      - name: Build Release
        run: cargo build --locked --release --verbose --target ${{ matrix.platform.target }}

      - name: Run Tests
        run: cargo test --locked --verbose --target ${{ matrix.platform.target }}

      - name: Upload Debug Build
        uses: actions/upload-artifact@v4
        with:
          name: 'kfc-parser-debug'
          path: target/${{ matrix.platform.target }}/debug/${{ matrix.platform.bin }}
          retention-days: 90
          if-no-files-found: error

      - name: Upload Release Build
        uses: actions/upload-artifact@v4
        with:
          name: 'kfc-parser'
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
          retention-days: 90
          if-no-files-found: error
