name: Rust Build and Test

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - name: Release
        uses: actions/upload-artifact@v4
        with:
          name: 'kfc-parser'
          path: target/debug/kfc-parser.exe
          retention-days: 90
          if-no-files-found: error
